<?PHP
/*********************************************************************************
 
 
 
 
 
 
 
 
 
 
 
 
 
 *

 
 

 
 *
 
 
 
 
 ********************************************************************************/

/**
 * THIS CLASS IS GENERATED BY MODULE BUILDER
 * PLEASE DO NOT CHANGE THIS CLASS
 * PLACE ANY CUSTOMIZATIONS IN {{$class.name}}
 */

{{foreach from=$class.requires item='require'}}
require_once('{{$require}}');
{{/foreach}}

class {{$class.name}}_sugar extends {{$class.extends}} {
	var $new_schema = true;
	var $module_dir = '{{$class.name}}';
	var $object_name = '{{$class.name}}';
	var $table_name = '{{$class.table_name}}';
	var $importable = {{if $class.importable}}true{{else}}false{{/if}};
	{{foreach from=$class.fields key='field' item='def'}}
	var ${{$field}};
	{{/foreach}}
	{{if empty($class.team_security)}}
	var $disable_row_level_security = true;
	{{/if}}
	function {{$class.name}}_sugar(){	
		parent::{{$class.extends}}();
	}
	
	{{if $class.acl}}
function bean_implements($interface){
		switch($interface){
			case 'ACL': return true;
		}
		return false;
}
	{{/if}}
	
}
?>